from __future__ import annotations

from .errors import (
    AdapterError,
    ConfigError,
    EMOSAuthError,
    EMOSNetworkError,
    EMOSServerError,
    EMOSValidationError,
    ErrorInfo,
    IndexError,
    IngestError,
    InvalidInputError,
    SegmentsFailedError,
    UnsupportedSourceError,
)
from .ids import build_group_id, build_message_id
from .models import (
    IngestReport,
    PlainTextContent,
    ReportError,
    ReportSummary,
    Segment,
    SegmentResult,
    Source,
    SourceContent,
    SourceResult,
    TranscriptContent,
    TranscriptLine,
    build_segment,
)

__all__ = [
    "AdapterError",
    "ConfigError",
    "EMOSAuthError",
    "EMOSNetworkError",
    "EMOSServerError",
    "EMOSValidationError",
    "ErrorInfo",
    "IndexError",
    "IngestError",
    "InvalidInputError",
    "SegmentsFailedError",
    "UnsupportedSourceError",
    "build_group_id",
    "build_message_id",
    "IngestReport",
    "PlainTextContent",
    "ReportError",
    "ReportSummary",
    "Segment",
    "SegmentResult",
    "Source",
    "SourceContent",
    "SourceResult",
    "TranscriptContent",
    "TranscriptLine",
    "build_segment",
]
