id: bibliotalk
url: "http://host.docker.internal:8009"
as_token: "<MATRIX_AS_TOKEN>"
hs_token: "<MATRIX_HS_TOKEN>"
sender_localpart: "bt_appservice"
rate_limited: false
namespaces:
  users:
    - exclusive: true
      regex: "@bt_.*:localhost"
  aliases:
    - exclusive: true
      regex: "#bt_.*:localhost"
  rooms: []

